### PR TITLE
[Feat|DETS] : Support for EDC v7

### PR DESCRIPTION
**Pull request by amoldashwant**
### Added
- Support for EDC v7

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by amoldashwant** [comment]
@sachinargade123 please review

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by almadigabor — CHANGES_REQUESTED** [review]
Please update all license headers in the PR according to [this guide](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header).

**Comment by amoldashwant** [comment]
> Please update all license headers in the PR according to [this guide](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header).

Changes done for the license headers. Please review

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
