### PR TITLE
fix: Updating helm lint

### PR DESCRIPTION
**Pull request by adkumar1**
- This PR is to update the helm upgrade job while linting the charts

### CODE REVIEW

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by almadigabor — APPROVED** [review]
LGTM

**Comment by almadigabor** [comment]
Hey @adkumar1 @adityagajbhiye9! Please resolve the merge conflict with the CHANGELOG.md file.

**Comment by adkumar1** [comment]
This PR is no longer needed.
Closing the PR

**Pull request closed without merging**
