### PR TITLE
chore(deps): configure maven dash plugin and keep DEPENDENCIES up-to-date

### PR DESCRIPTION
**Pull request by SebastianBezold**
## Description

This PR adds an up-to-date version of the `DEPENDENCIES` file. 
Additionally, the maven Dash plugin declaration in the `pom.xml` is configured with the right `includeScope` and `project`

An up-to-date `DEPENDENCIES` file is mandatory for #19

### CODE REVIEW

**Comment by SebastianBezold** [comment]
Hi @adkumar1, friendly reminder. We definitely need the up-to-date `DEPENDENCIES` fiel before creating a release

**Comment by adkumar1** [comment]
Approved from my side

**Comment by MehranRoshandel** [comment]
@SebastianBezold as talk yesterday Aditya has approved it. please merge and close

**Comment by SebastianBezold** [comment]
Hi @MehranRoshandel, merged. I'll create the release now.
@adkumar1 please keep the `DEPENDENCIES` file up-to-date from now on on every PR. 
We need to find "restricted" or "rejected" libraries as soon as possible

**Pull request merged**
